### ISSUE TITLE
Shield not gaining any experience

### ISSUE THREAD

**Issue by AemonJape** [Pyre540/tinkers-levelling-addon#10]
The version of each are: 
Minecraft 1.18.2, Forge 40.2.0, Mantle 1.9.43, Tinkers Construct 3.6.3.111, TinkersLevellingAddon 1.2.0

Issue: Shields do not gain xp. 
I've tried being damaged while using it, attacking with shield, putting thorns on it and attacking, and mining with it. Nothing works.
I've checked the config files, and there is not configs for shields, so maybe it is not implemented. 
However, from the description, I expected it to work, and the modifier can be applied to the shield.

Please 1) develop this feature or 2) clarify it doesn't work on shields, or make it impossible to apply it on them. 

As a side note, the 'reflecting' modifier that can be put on shields can also deal indirect damage, and blocking with a shield barely causes any health damage, so I think it would be better if a different mechanism for xp gain (such as per blocked attack) was in place.

**Comment by Pyre540** [comment]
Hey!

Unfortunately, as of version 1.2.0, shields can't be leveled up.
I'm already working on the appropriate update, but due to the lack of time recently, I can't say when it will be released.

**Comment by border999** [comment]
Ironically I opened this same issue on the wrong tinkers leveling mod, turns out it had the same issue and it just finished patching that problem.

**Comment by border999** [comment]
do we have a progress report or ETA on this update? I'll drop what they did for theirs, might be helpful

**Comment by border999** [comment]
https://github.com/embeddedt/TinkerLeveling/commit/2530bbae24deb4477abafe1c43dfb4fc741a94a5

**Comment by Pyre540** [comment]
Hey!
Update is out :)
