### ISSUE TITLE
Singleplayer Client Stuck at Max Level Five(5)

### ISSUE THREAD

**Issue by GuardianMilky** [Pyre540/tinkers-levelling-addon#14]
Is it possible in client? Or is it only server sided configs that can change the max level?

```
#Client only settings
[client]
	#If true, shows chat message on tool level ups.
	message = true
	#If true, uses alternative level name suffix for high level tools.
	#Instead of appending '+' signs for each consecutive level appearance, +1, +2, +3, etc. notation will be used.
	squashPluses = false
	#No comment
	#Allowed Values: NONE, CHIME, SNARE_DRUM, YAY
	sound = "CHIME"
```
	
This is the only config I have which is from **tinkerslevellingaddon-client.toml**

Yes, I did read the comments at the curseforge page, you said there's **maxLevel** setting in the server file but in client, there's none which makes sense since it is client. My problem is not having the server-config, is there a way to get that?

**Comment by Pyre540** [comment]
You can find info about config file locations in FAQ section on CF page or in GitHub readme.
```
For local/singleplayer instances you can find config file in .minecraft/saves/<world_name>/serverconfig/tinkerslevellingaddon-server.toml
```
