### ISSUE TITLE
Crash when trying to view Improvable ability description in Mighty Smelting book

### ISSUE THREAD

**Issue by RoselynnT** [Pyre540/tinkers-levelling-addon#15]
When trying to go to the page containing the description for the Improvable ability (in the Mighty Smelting guide book) the game crashes due to an issue rendering the screen (1.19.2)
[crash-2024-08-13_21.23.27-client.txt](https://github.com/user-attachments/files/16607107/crash-2024-08-13_21.23.27-client.txt)

**Comment by Pyre540** [comment]
Hey!
Thanks for the report :) Issue seems to be caused by missing modifier texture for Tinkers Reforged Greatsword.
Fixed it and released update for the addon (1.4.1). You can download it from Github Releases for now. It should be available via CursedForge/Modrinth soon.
