### ISSUE TITLE
no server config file

### ISSUE THREAD

**Issue by nydfhh** [Pyre540/tinkers-levelling-addon#6]
I can't get a server config file to generate only the client config

**Comment by Pyre540** [comment]
Server config is stored in a server/save specific "serverconfig" directory. So basically in `.minecraft/saves/<level_name>/serverconfig` for Singleplayer Instances and in `<server_folder>/world/serverconfig` for Server Instances.

If config file is not present there:
1. What MC version and Addon version are you running?
2. Is this singleplayer world or multiplayer server (this should not matter really)?
3. Are you using other mods (other than Tconstruct/Mantle of course). Can you reproduse this issue using minimal set of mods?

**Comment by nydfhh** [comment]
It is there I just thought it would be in .minecraft/config

**Comment by Pyre540** [comment]
Common config is stored in `.minecraft/config` or `<server_folder>/config` ;)
