### ISSUE TITLE
example datapack for recipe override does not work [1.18.2]

### ISSUE THREAD

**Issue by howardxu23** [Pyre540/tinkers-levelling-addon#8]
I installed the datapack in accordance to the wiki, which says to put the zip file that is provided into the /saves/[worldname]/datapacks folder. I did that and it does not actually change the recipe, but other datapacks seems to function correctly.

**Comment by DreamSmith** [comment]
The zip is incorrectly packaged, you can work around by unzipping the file and then creating the a new zip from within the folder.

**Comment by Pyre540** [comment]
Ah, yes, the additional, nested directory. I corrected dir structure and reuploaded zipped datapacks. Sorry for inconvenience and thanks!
